logging:
  level:
    '[org.springframework.web]': debug

spring:
  datasource:
    url: jdbc:mariadb://211.175.134.192:3306/daebak_schema?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: '!Q2w3e4r5t'
    driver-class-name: org.mariadb.jdbc.Driver